# Generated by Django 4.2.7 on 2023-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_password_alter_customuser_username_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
