# Generated by Django 4.2.7 on 2023-11-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_follow_followed"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="book",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
